<a href="https://colab.research.google.com/github/LiorBac/learning-ml-automation/blob/main/week1_basics/day1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📘 NumPy Basics – Day 1

NumPy is the core library for numerical computing in Python. It provides:

- Fast and efficient arrays (much faster than Python lists)  
- Mathematical operations (linear algebra, statistics, random numbers)  
- Tools for scientific computing  

Today we will explore the fundamentals step by step.



---
## 🔹 Importing NumPy

The convention is to import NumPy as `np`.  
This makes it shorter to use in code.

👉 Example:
```python
import numpy as np


In [2]:
import numpy as np


---
## 🔹 Creating Arrays

NumPy arrays can be created in different ways:

- From Python lists: `np.array([1,2,3])`  
- With zeros: `np.zeros((rows, cols))`  
- With ones: `np.ones((rows, cols))`  
- With a range of numbers: `np.arange(start, stop, step)`  
- With evenly spaced numbers: `np.linspace(start, stop, num_points)`  


In [3]:
a=np.array([1,2,3])
print(a)

array([1, 2, 3])

In [4]:
b=np.zeros((2,3))
print(b)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.ones((3, 3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
d = np.arange(0, 12 , 3)
print(d)

[0 3 6 9]


In [10]:
e = np.linspace(0, 1, 5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


---
## 🔹 Array Properties

Every NumPy array has useful attributes:

- `.shape` → dimensions (rows, columns)  
- `.dtype` → data type (int, float, etc.)  
- `.size` → total number of elements  

You can also reshape arrays with `.reshape(new_rows, new_cols)`.


In [13]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
print(arr.shape)

(12,)


In [17]:
print(arr.dtype)

int64


In [18]:
print(arr.size)

12


In [20]:
print(arr.reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
print(arr.reshape(2, 6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


---
## 🔹 Indexing & Slicing

Like Python lists, NumPy arrays support indexing and slicing:

- Access an element: `arr[0]`  
- Access a slice: `arr[2:6]`  
- Use conditions: `arr[arr > 5]` (boolean indexing)  

In [22]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [23]:
print(arr[0])

0


In [25]:
print(arr[1:4])

[2 4 6]


In [26]:
print(arr[arr > 4])

[6 8]


In [27]:
print(arr > 2)

[False False  True  True  True]


---
## 🔹 Operations

NumPy allows **element-wise operations** and **broadcasting**:

- Add arrays: `x + y`  
- Multiply arrays: `x * y`  
- Aggregate functions:  
  - `arr.sum()`  
  - `arr.mean()`  
  - `arr.max()`, `arr.min()`  


In [29]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [31]:
b = np.arange(2,15,3)
print(b)

[ 2  5  8 11 14]


In [32]:
print(a+b)

[ 2  7 12 17 22]


In [33]:
print(a*b)

[  0  10  32  66 112]


In [34]:
print(a*5)

[ 0 10 20 30 40]


In [36]:
print(a.sum())

20


In [37]:
print(a.mean())

4.0


In [38]:
print(a.max())
print(a.min())

8
0


---
## 🔹 Random Numbers

NumPy includes a random module:

- `np.random.rand(shape)` → random numbers between 0 and 1  
- `np.random.randn(shape)` → random numbers from normal distribution  
- `np.random.randint(low, high, size)` → random integers in a range  


In [39]:
a = np.random.rand(2,2)
print(a)

[[0.3516901  0.95851937]
 [0.3933016  0.388322  ]]


In [40]:
a = np.random.randn(2,2)
print(a)

[[ 0.74141465 -0.45005984]
 [-0.44657532  0.44277007]]


In [41]:
a = np.random.randint(0,10,4)
print(a)

[7 5 6 0]


---
## ✍️ Mini Exercises

1. Create a 3×3 array with values from 0 to 8.  
2. Create a random 5×5 matrix and find its maximum value.  
3. Generate an array of 100 random numbers and compute mean & standard deviation.  
4. Reshape a 1D array of 16 elements into a 4×4 matrix.  


### 📝 Exercise 1
Create a 3×3 array with values from 0 to 8.


In [44]:
a = np.arange(9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 📝 Exercise 2
Create a random 5×5 matrix and find its maximum value.


In [47]:
a = np.random.rand(5,5)
print(a)
b = a.max()
print(b)

[[0.80051695 0.51881329 0.93385531 0.08999162 0.61940522]
 [0.6436836  0.31660433 0.32744892 0.79858485 0.96171361]
 [0.21229287 0.89979817 0.66120769 0.13797292 0.94064317]
 [0.82908432 0.38322534 0.04233595 0.02449641 0.90317579]
 [0.52900678 0.87063754 0.22420494 0.48836189 0.89351966]]
0.9617136118979496


### 📝 Exercise 3
Generate an array of 100 random numbers and compute mean & standard deviation.  

In [48]:
a=np.random.rand(100)
b=a.mean()
c=a.std()
print(a)
print(b)
print(c)

[0.75514873 0.3714984  0.42272172 0.98808807 0.51459275 0.63873088
 0.91504888 0.90938379 0.32545038 0.88652264 0.30624971 0.33465806
 0.70525868 0.47725187 0.63371017 0.22638334 0.43312531 0.40344211
 0.62774977 0.28752819 0.2149316  0.77771854 0.11533783 0.37868283
 0.19488329 0.47222775 0.06892684 0.31204961 0.6124139  0.56959768
 0.75605989 0.37430551 0.53474256 0.05963336 0.91013205 0.80168386
 0.66254148 0.93330248 0.43069015 0.03372807 0.93404899 0.32977921
 0.93642023 0.50547829 0.33566854 0.5780479  0.61091527 0.07833575
 0.03376732 0.71432111 0.52989433 0.8354064  0.20122308 0.80828816
 0.83013051 0.54090647 0.34391102 0.55762124 0.37983791 0.53912049
 0.23714475 0.055377   0.583995   0.28893344 0.25941824 0.52861773
 0.85489236 0.71508804 0.58078777 0.18938346 0.95901218 0.42820967
 0.27450706 0.39357271 0.13402346 0.41221401 0.21644972 0.07657331
 0.23801079 0.57630764 0.38555799 0.01015718 0.64054503 0.44938018
 0.45317166 0.77250807 0.34236381 0.92601356 0.22851041 0.9258

### 📝 Exercise 4
Reshape a 1D array of 16 elements into a 4×4 matrix.

In [52]:
a = np.zeros(16)
b = a.reshape(4,4)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
